apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  labels:
    app.kubernetes.io/name: {{ include "squid.name" . }}
    helm.sh/chart: {{ include "squid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "squid.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "squid.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 3128
            protocol: TCP
        livenessProbe:
          exec:
            command:
              - /usr/sbin/squid 
              - -k 
              - parse
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
              - /usr/sbin/squid 
              - -k 
              - parse
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
          - name: squid-config
            mountPath: /etc/squid/squid.conf
            subPath: squid.conf
        resources:
      volumes:
        - name: squid-config
          configMap:
            name: squid-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
