apiVersion: v1
kind: Service
metadata:
  name: {{ include "squid.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "squid.name" . }}
    helm.sh/chart: {{ include "squid.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ tpl .Values.service.annotations . | nindent 4 | trim }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "squid.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

