{{- if and .Values.landbAlias.enabled .Values.landbAlias.admissionWebhooks.enabled .Values.landbAlias.admissionWebhooks.patch.enabled (not .Values.landbAlias.admissionWebhooks.certManager.enabled) }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ template "landb-sync.fullname" . }}-admission-patch
  namespace: {{ template "landb-sync.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "landb-sync.name" $ }}-admission-patch
{{ include "landb-sync.labels" . | indent 4 }}
spec:
  ttlSecondsAfterFinished: 0
  template:
    metadata:
      name:  {{ template "landb-sync.fullname" . }}-admission-patch
{{- with .Values.landbAlias.admissionWebhooks.patch.podAnnotations }}
      annotations:
{{ toYaml .  | indent 8 }}
{{- end }}
      labels:
        app: {{ template "landb-sync.name" $ }}-admission-patch
{{ include "landb-sync.labels" . | indent 8 }}
    spec:
      {{- if .Values.landbAlias.admissionWebhooks.patch.priorityClassName }}
      priorityClassName: {{ .Values.landbAlias.admissionWebhooks.patch.priorityClassName }}
      {{- end }}
      containers:
        - name: patch
          {{- if .Values.landbAlias.admissionWebhooks.patch.image.sha }}
          image: {{ .Values.landbAlias.admissionWebhooks.patch.image.repository }}:{{ .Values.landbAlias.admissionWebhooks.patch.image.tag }}@sha256:{{ .Values.landbAlias.admissionWebhooks.patch.image.sha }}
          {{- else }}
          image: {{ .Values.landbAlias.admissionWebhooks.patch.image.repository }}:{{ .Values.landbAlias.admissionWebhooks.patch.image.tag }}
          {{- end }}
          imagePullPolicy: {{ .Values.landbAlias.admissionWebhooks.patch.image.pullPolicy }}
          args:
            - patch
            - --webhook-name={{ template "landb-sync.fullname" . }}-admission
            - --namespace={{ template "landb-sync.namespace" . }}
            - --secret-name={{ template "landb-sync.fullname" . }}-admission
            - --patch-failure-policy={{ .Values.landbAlias.admissionWebhooks.failurePolicy }}
            - --patch-mutating=false
          resources:
{{ toYaml .Values.landbAlias.admissionWebhooks.patch.resources | indent 12 }}
      restartPolicy: OnFailure
      serviceAccountName: {{ template "landb-sync.fullname" . }}-admission
      {{- with .Values.landbAlias.admissionWebhooks.patch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.landbAlias.admissionWebhooks.patch.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.landbAlias.admissionWebhooks.patch.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
{{- if .Values.landbAlias.admissionWebhooks.patch.securityContext }}
      securityContext:
{{ toYaml .Values.landbAlias.admissionWebhooks.patch.securityContext | indent 8 }}
{{- end }}
{{- end }}