{{- if and .Values.landbAlias.enabled .Values.landbAlias.admissionWebhooks.enabled .Values.landbAlias.admissionWebhooks.patch.enabled (not .Values.landbAlias.admissionWebhooks.certManager.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name:  {{ template "landb-sync.fullname" . }}-admission
  namespace: {{ template "landb-sync.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: {{ template "landb-sync.name" $ }}-admission
{{ include "landb-sync.labels" . | indent 4 }}
{{- end }}