apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus
    release: prometheus-operator
  name: cern.monit-base.cluster.rules
  namespace: kube-system
spec:
  groups:
  - interval: {{ .Values.evaluationInterval }}
    name: cern.monit-base.cluster.rules
    rules:
    - expr: sum(avg_over_time(kube_node_status_capacity_cpu_cores[{{ .Values.metricWindow }}]))
      labels: {aggregate: {{ .Values.evaluationInterval }}, monit_forward: "true", monit_metric_name: "kube_node_status_capacity_cpu_cores"}
      record: cern:cluster:cpu:capacity:total
    - expr: sum(avg_over_time(kube_pod_container_resource_requests_cpu_cores[{{ .Values.metricWindow }}]))
      labels: {aggregate: {{ .Values.evaluationInterval }}, monit_forward: "true", monit_metric_name: "kube_pod_container_resource_requests_cpu_cores"}
      record: cern:cluster:cpu:requests:total
    - expr: sum(avg_over_time(kube_node_status_allocatable_cpu_cores[{{ .Values.metricWindow }}]))
      labels: {aggregate: {{ .Values.evaluationInterval }}, monit_forward: "true", monit_metric_name: "kube_node_status_allocatable_cpu_cores"}
      record: cern:cluster:cpu:allocatable:total
    - expr: sum(max_over_time(kube_node_info[{{ .Values.metricWindow }}]))
      labels: {aggregate: {{ .Values.evaluationInterval }}, monit_forward: "true", monit_metric_name: "kube_node_info"}
      record: cern:cluster:nodes:total:max
    - expr: sum(avg_over_time(kube_node_status_allocatable_memory_bytes[{{ .Values.metricWindow }}]))
      labels: {aggregate: {{ .Values.evaluationInterval }}, monit_forward: "true", monit_metric_name: "kube_node_status_allocatable_memory_bytes"}
      record: cern:cluster:memory:allocatable:total
    - expr: sum(avg_over_time(kube_node_status_capacity_memory_bytes[{{ .Values.metricWindow }}]))
      labels: {aggregate: {{ .Values.evaluationInterval }}, monit_forward: "true", monit_metric_name: "kube_node_status_capacity_memory_bytes"}
      record: cern:cluster:memory:capacity:total
    - expr: sum(avg_over_time(kube_pod_container_resource_requests_memory_bytes[{{ .Values.metricWindow }}]))
      labels: {aggregate: {{ .Values.evaluationInterval }}, monit_forward: "true", monit_metric_name: "kube_pod_container_resource_requests_memory_bytes"}
      record: cern:cluster:memory:requested:total
