{{- if .Values.frontier.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontier-squid
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: frontier-squid
spec:
  selector:
    matchLabels:
      k8s-app: frontier-squid
  template:
    metadata: 
      labels:
        k8s-app: frontier-squid
    spec:
      containers:
      - name: frontier-squid
        image: {{ .Values.frontier.image }}
        imagePullPolicy: {{ .Values.frontier.imagePullPolicy }}
        resources:
{{ toYaml .Values.frontier.resources | indent 10 }}
        ports:
        - containerPort: 3128
        volumeMounts:
          - name: config-map-frontier
            mountPath: /etc/squid/customize_k8s.sh
            subPath: customize_k8s.sh
      priorityClassName: {{ .Values.frontier.priorityClassName }}
      volumes:
      - name: config-map-frontier
        configMap:
          name: config-map-frontier
          defaultMode: 0777
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: frontier-squid
  name: frontier-squid
spec:
  ports:
  - port: 3128
    protocol: TCP
    targetPort: 3128
  selector:
    k8s-app: frontier-squid
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
data:
  customize_k8s.sh: |
    #!/bin/bash
    #
    # Edit customize.sh as you wish to customize squid.conf.
    # It will not be overwritten by upgrades.
    # See customhelps.awk for information on predefined edit functions.
    # In order to test changes to this, run this to regenerate squid.conf:
    #	service frontier-squid
    # and to reload the changes into a running squid use
    #	service frontier-squid reload
    # Avoid single quotes in the awk source or you have to protect them from bash.
    #

    awk --file `dirname $0`/customhelps.awk --source '{
    setoption("acl NET_LOCAL src", "0.0.0.0/0 172.16.0.0/12 192.168.0.0/16 fc00::/7 fe80::/10")
    setoption("cache_mem", "128 MB")
    setoptionparameter("cache_dir", 3, "10000")
    print
    }'
metadata:
  name: config-map-frontier
  namespace: {{ .Release.Namespace }}
{{- end }}
