#
# Local persistent storage for cvmfs base dir
#
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvmfs-root
# Local storage does not need a provisioner
provisioner: kubernetes.io/no-provisioner
# Give it out as-is
reclaimPolicy: {{ .Values.reclaimPolicy }}
volumeBindingMode: {{ .Values.volumeBindingMode }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cvmfs-root
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ .Values.reclaimPolicy }}
  storageClassName: cvmfs-root
  local:
    path: {{ .Values.rootPrefix }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: NotIn
          values:
          -  fake
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cvmfs-root
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: cvmfs-root
