apiVersion: v1
kind: Secret
metadata:
  name: condor-gsi-cert
  labels:
    app: {{ template "condor-startd.name" . }}
    chart: {{ template "condor-startd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  hostcert.pem: {{ .Values.gsi.certificate | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: condor-gsi-key
  labels:
    app: {{ template "condor-startd.name" . }}
    chart: {{ template "condor-startd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  hostkey.pem: {{ .Values.gsi.key | b64enc | quote }}
