{{- if and .Values.plugin.metrics.enabled .Values.plugin.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvidia-gpu-metrics
  {{- if .Values.plugin.metrics.serviceMonitor.namespace }}
  namespace: {{ .Values.plugin.metrics.serviceMonitor.namespace }}
  {{- end }}
  labels:
    k8s-app: nvidia-gpu-device-plugin
    chart: nvidia-gpu
    release: prometheus-operator
    {{- if .Values.plugin.metrics.serviceMonitor.additionalLabels }}
    {{ toYaml .Values.plugin.metrics.serviceMonitor.additionalLabels | indent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: {{ .Values.plugin.metrics.serviceMonitor.scrapeInterval }}
      {{- if .Values.plugin.metrics.serviceMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
  {{- if .Values.plugin.metrics.serviceMonitor.namespaceSelector }}
  namespaceSelector:
    {{ toYaml .Values.plugin.metrics.serviceMonitor.namespaceSelector | indent 4 -}}
  {{ else }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end }}
  selector:
    matchLabels:
      k8s-app: nvidia-gpu-device-plugin
      release: {{ .Release.Name }}
{{- end }}
