apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus
    release: prometheus-operator
  name: cern.prometheus-kube-prometheus-node-recording.aggregated-rules.yaml
  namespace: kube-system
spec:
  groups:
  - interval: '{{.Values.evaluationInterval}}'
    name: cern.kube-prometheus-node-recording.aggregated-rules
    rules:
    - expr: sum(rate(node_cpu_seconds_total{mode!="idle",mode!="iowait"}[{{.Values.metricWindow}}]))
        BY (instance)
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_cpu:rate:sum
    - expr: sum((node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}))
        BY (instance)
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_filesystem_usage:sum
    - expr: sum(rate(node_network_receive_bytes_total[{{.Values.metricWindow}}]))
        BY (instance)
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_network_receive_bytes:rate:sum
    - expr: sum(rate(node_network_transmit_bytes_total[{{.Values.metricWindow}}]))
        BY (instance)
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_network_transmit_bytes:rate:sum
    - expr: sum(rate(node_cpu_seconds_total{mode!="idle",mode!="iowait"}[{{.Values.metricWindow}}]))
        WITHOUT (cpu, mode) / ON(instance) GROUP_LEFT() count(sum(node_cpu_seconds_total)
        BY (instance, cpu)) BY (instance)
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_cpu:ratio
    - expr: sum(rate(node_cpu_seconds_total{mode!="idle",mode!="iowait"}[{{.Values.metricWindow}}]))
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:cluster:node_cpu:sum_rate5m
    - expr: cluster:node_cpu_seconds_total:rate5m / count(sum(node_cpu_seconds_total)
        BY (instance, cpu))
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:cluster:node_cpu:ratio
