apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus
    release: prometheus-operator
  name: cern.prometheus-node-exporter.aggregated-rules.yaml
  namespace: kube-system
spec:
  groups:
  - interval: '{{.Values.evaluationInterval}}'
    name: cern.node-exporter.aggregated-rules
    rules:
    - expr: "count without (cpu) (\n  count without (mode) (\n    node_cpu_seconds_total{job=\"\
        node-exporter\"}\n  )\n)"
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_num_cpu:sum
    - expr: "1 - avg without (cpu, mode) (\n  rate(node_cpu_seconds_total{job=\"node-exporter\"\
        , mode=\"idle\"}[{{.Values.metricWindow}}])\n)"
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_cpu_utilisation:rate1m
    - expr: "(\n  node_load1{job=\"node-exporter\"}\n/\n  instance:node_num_cpu:sum{job=\"\
        node-exporter\"}\n)"
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_load1_per_cpu:ratio
    - expr: "1 - (\n  node_memory_MemAvailable_bytes{job=\"node-exporter\"}\n/\n \
        \ node_memory_MemTotal_bytes{job=\"node-exporter\"}\n)"
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_memory_utilisation:ratio
    - expr: rate(node_vmstat_pgmajfault{job="node-exporter"}[{{.Values.metricWindow}}])
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_vmstat_pgmajfault:rate1m
    - expr: rate(node_disk_io_time_seconds_total{job="node-exporter", device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+"}[{{.Values.metricWindow}}])
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance_device:node_disk_io_time_seconds:rate1m
    - expr: rate(node_disk_io_time_weighted_seconds_total{job="node-exporter", device=~"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+"}[{{.Values.metricWindow}}])
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance_device:node_disk_io_time_weighted_seconds:rate1m
    - expr: "sum without (device) (\n  rate(node_network_receive_bytes_total{job=\"\
        node-exporter\", device!=\"lo\"}[{{.Values.metricWindow}}])\n)"
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_network_receive_bytes_excluding_lo:rate1m
    - expr: "sum without (device) (\n  rate(node_network_transmit_bytes_total{job=\"\
        node-exporter\", device!=\"lo\"}[{{.Values.metricWindow}}])\n)"
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_network_transmit_bytes_excluding_lo:rate1m
    - expr: "sum without (device) (\n  rate(node_network_receive_drop_total{job=\"\
        node-exporter\", device!=\"lo\"}[{{.Values.metricWindow}}])\n)"
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_network_receive_drop_excluding_lo:rate1m
    - expr: "sum without (device) (\n  rate(node_network_transmit_drop_total{job=\"\
        node-exporter\", device!=\"lo\"}[{{.Values.metricWindow}}])\n)"
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
      record: cern:instance:node_network_transmit_drop_excluding_lo:rate1m
