apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: prometheus
    release: prometheus-operator
  name: cern.prometheus-kube-scheduler.aggregated-rules.yaml
  namespace: kube-system
spec:
  groups:
  - interval: '{{.Values.evaluationInterval}}'
    name: cern.kube-scheduler.aggregated-rules
    rules:
    - expr: histogram_quantile(0.99, sum(rate(scheduler_e2e_scheduling_duration_seconds_bucket{job="kube-scheduler"}[{{.Values.metricWindow}}]))
        without(instance, pod))
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
        quantile: '0.99'
      record: cern:cluster_quantile:scheduler_e2e_scheduling_duration_seconds:histogram_quantile
    - expr: histogram_quantile(0.99, sum(rate(scheduler_scheduling_algorithm_duration_seconds_bucket{job="kube-scheduler"}[{{.Values.metricWindow}}]))
        without(instance, pod))
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
        quantile: '0.99'
      record: cern:cluster_quantile:scheduler_scheduling_algorithm_duration_seconds:histogram_quantile
    - expr: histogram_quantile(0.99, sum(rate(scheduler_binding_duration_seconds_bucket{job="kube-scheduler"}[{{.Values.metricWindow}}]))
        without(instance, pod))
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
        quantile: '0.99'
      record: cern:cluster_quantile:scheduler_binding_duration_seconds:histogram_quantile
    - expr: histogram_quantile(0.9, sum(rate(scheduler_e2e_scheduling_duration_seconds_bucket{job="kube-scheduler"}[{{.Values.metricWindow}}]))
        without(instance, pod))
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
        quantile: '0.9'
      record: cern:cluster_quantile:scheduler_e2e_scheduling_duration_seconds:histogram_quantile
    - expr: histogram_quantile(0.9, sum(rate(scheduler_scheduling_algorithm_duration_seconds_bucket{job="kube-scheduler"}[{{.Values.metricWindow}}]))
        without(instance, pod))
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
        quantile: '0.9'
      record: cern:cluster_quantile:scheduler_scheduling_algorithm_duration_seconds:histogram_quantile
    - expr: histogram_quantile(0.9, sum(rate(scheduler_binding_duration_seconds_bucket{job="kube-scheduler"}[{{.Values.metricWindow}}]))
        without(instance, pod))
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
        quantile: '0.9'
      record: cern:cluster_quantile:scheduler_binding_duration_seconds:histogram_quantile
    - expr: histogram_quantile(0.5, sum(rate(scheduler_e2e_scheduling_duration_seconds_bucket{job="kube-scheduler"}[{{.Values.metricWindow}}]))
        without(instance, pod))
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
        quantile: '0.5'
      record: cern:cluster_quantile:scheduler_e2e_scheduling_duration_seconds:histogram_quantile
    - expr: histogram_quantile(0.5, sum(rate(scheduler_scheduling_algorithm_duration_seconds_bucket{job="kube-scheduler"}[{{.Values.metricWindow}}]))
        without(instance, pod))
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
        quantile: '0.5'
      record: cern:cluster_quantile:scheduler_scheduling_algorithm_duration_seconds:histogram_quantile
    - expr: histogram_quantile(0.5, sum(rate(scheduler_binding_duration_seconds_bucket{job="kube-scheduler"}[{{.Values.metricWindow}}]))
        without(instance, pod))
      labels:
        aggregate: '{{.Values.evaluationInterval}}'
        quantile: '0.5'
      record: cern:cluster_quantile:scheduler_binding_duration_seconds:histogram_quantile
