apiVersion: v1
kind: ConfigMap
metadata:
  name: eosxd-config
  labels:
    app: {{ template "eosxd.name" . }}
    chart: {{ template "eosxd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- $config := .Values.config}}
  {{- range $area, $mountpoints := .Values.mounts }}
    {{- if $mountpoints }}
      {{- range $mountpoint, $letters := $mountpoints }}
        {{- if $letters }}
  fuse.{{ $mountpoint }}.conf: |+
      {{ template "mountpoint.config" (dict "name" $mountpoint "server" $mountpoint "remote" $area "config" $config "extra_config" (dict "bind" $letters)) }}
        {{- else }}
  fuse.{{ $area }}.conf: |+
      {{ template "mountpoint.config" (dict "name" $area "server" $mountpoint  "remote" $area "config" $config) }}
        {{- end }}
      {{- end }}
    {{- else }}
  fuse.{{ $area }}.conf: |+
      {{ template "mountpoint.config" (dict "name" $area "server" $area "remote" $area "config" $config) }}

    {{- end }}
  {{- end }}