kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "landb-sync.fullname" . }}
  labels:
    app: {{ template "landb-sync.name" . }}
{{ include "landb-sync.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "landb-sync.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "landb-sync.fullname" . }}
