apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ template "landb-sync.namespace" . }}
  name: {{ template "landb-sync.fullname" . }}
  labels:
    app: {{ template "landb-sync.name" . }}
{{ include "landb-sync.labels" . | indent 4 }}
