apiVersion: v1
kind: Service
metadata:
  name: {{ template "landb-sync.fullname" . }}
  namespace: {{ template "landb-sync.namespace" . }}
  labels:
    app: {{ template "landb-sync.name" . }}
{{ include "landb-sync.labels" . | indent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 443
    name: webhook
  selector:
    app: {{ template "landb-sync.name" . }}
{{ include "landb-sync.labels" . | indent 4 }}
