apiVersion: v1
name: eosxd
version: 5.1.27-1
appVersion: "5.1.27-1.1"
description: A Helm chart for eosxd
home: http://eos.web.cern.ch/
sources:
  - https://gitlab.cern.ch/helm/charts/cern/tree/master/eosxd
icon: http://eos.web.cern.ch/sites/eos.web.cern.ch/themes/eos-webpage/img/logos/EOS_logo1.svg
